#include<stdio.h>
int main(void)
{
    int n,k,t,i;
    scanf("%d",&t);
    for(i=0;i<t;i++)
    {
        scanf("%d%d",&n,&k);
        int a[n],b[n],j,l,temp,sum=0;
        for(j=0;j<n;j++)
        {
            scanf("%d",&a[j]);
        }
        for(j=0;j<n;j++)
        {
            scanf("%d",&b[j]);
        }
        for(l=0;l<n;l++)
        {
            for(j=0;j<n-1;j++)
        {
            if(a[j]>a[j+1])
            {
                temp=a[j];
                a[j]=a[j+1];
                a[j+1]=temp;
            }
            if(b[j]<b[j+1])
            {
                temp=b[j];
                b[j]=b[j+1];
                b[j+1]=temp;
            }
        }
        }
        for(j=0;j<k;j++)
        {
            if(b[j]>a[j])
                a[j]=b[j];
        }
        for(j=0;j<n;j++)
        {
            sum=sum+a[j];
        }
        printf("%d\n",sum);
    }
}
