#include<stdio.h>
#include<string.h>
int main(void)
{
    char s[110],s1[110],s2[110],s3[110];
    int i=0,n1=0,n2=0,n3=0,c1=0,c2=0;
    scanf("%s",s);
    while(1)
    {
        if(s[i]=='\0')
        {
            if(c1==i)
            {
                s1[n1-1]='\0';
                s1[n1]='\0';
            }
            else
            {
                s1[n1]='\0';
            }
            if(n1-1==i)
            {
                s1[n1-1]='\0';
                s1[n1]='\0';
            }
            if(c2==i-n1)
            {
                s2[n2-1]='\0';
                s2[n2]='\0';
            }
            else
            {
                s2[n2]='\0';
            }
            if(n2-1==i)
            {
                s2[n2-1]='\0';
                s2[n2]='\0';
            }
            s3[n3-1]='\0';
            s3[n3]='\0';
            break;
        }
        else if(s[i]=='1')
        {
            s1[n1]='1';
            n1++;
            s1[n1]='+';
            n1++;
            c1++;
        }
        else if(s[i]=='2')
        {
            s2[n2]='2';
            n2++;
            s2[n2]='+';
            n2++;
            c2++;
        }
        else if(s[i]=='3')
        {
            s3[n3]='3';
            n3++;
            s3[n3]='+';
            n3++;
        }
        i++;
    }
    strcat(s1,s2);
    strcat(s1,s3);
    printf("%s\n",s1);
}
